# 项目相关配置
project:
  # 名称
  name: getoffer
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2019
  #站点配置
  site:
    host: https://getoffer.xiliangmen.com
    staticHost: https://getoffer.xiliangmen.com
    whiteDomainList: localhost,xiliangmen.com
    siteDirPath: /
  #swagger 文档配置
  swagger:
    title: 熊猫体测微信小程序扫码以及个人中心接口
    description: 开发人员太懒，没有写描述
    contactName: Fengyu
    contactEmail: 475788922@qq.com
    contactUrl: https://getoffer.xiliangmen.com/doc.html
    version: 1.0


mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.belong
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    #刷新mapper 调试神器
    db-config:
      id-type: UUID
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
